### ISSUE TITLE
Support for Python 3.11

### ISSUE THREAD

**Issue by fcotizelati** [LSST-sersag/pyzdcf#2]
Hello,

I am writing to inquire about the possibility of extending the compatibility of `pyzdcf` to Python 3.11. I noticed that the current version specifies compatibility with Python versions >=3.8 and <3.11. Given the advancements and improvements introduced in Python 3.11, updating `pyzdcf` to be compatible with this version would be highly beneficial for users who have upgraded or plan to upgrade their Python environments. Is there a technical limitation that prevents `pyzdcf` from supporting Python 3.11, or is it something that could be looked into for future releases? Any insights or plans regarding this matter would be greatly appreciated.

Thank you very much in advance!

**Comment by cefeida42** [comment]
Hello Francesco,

thank you for your interest in `pyzdcf`! There should be no technical limitations for this. I will revise the code and make sure it is compatible with Python 3.11 in the following weeks.

Cheers!

**Comment by fcotizelati** [comment]
Hello, I wanted to ask if it was possible to revise the code to make it compatible with versions of Python >= 3.10 or at least with Python 3.11. Are there any updates in this regard? Thanks!

**Comment by cefeida42** [comment]
Hello Francesco,

I added support for Python 3.11, let me know if you have problems with the new version. I still have to make some adjustments in order to support Python 3.12. Thanks for your interest!

**Comment by fcotizelati** [comment]
Hello Isidora,

Thank you very much for your work on this! I have just successfully tested the module in a Python 3.11 environment :)
